### ISSUE TITLE
if attendee edits hotel request to decline space after he's already been approved, he's still approved

### ISSUE THREAD

**Issue by binary1230** [magfest/hotel#18]
repro:
- staffer requests hotel space
- admin approves it
- staffer edits hotel space request to decline all nights

expected:
- staffer is no longer able to see any setup or teardown shifts

actual
- staffer can still see setup or teardown shifts

I think it might be as simple as in `HotelRequests.decline()` we may need to add a `self.approved = False`

**Comment by EliAndrewC** [comment]
I think the current behavior might be preferable.  If someone ends up being approved for setup nights and then declines their hotel space, it might just mean that they decided to room with a friend or something.  Allowing them to still take setup shifts seems reasonable in that case.

**Comment by binary1230** [comment]
cool, sounds fine to me.  I added a test in #17 that explicitly codifies this behavior
