### ISSUE TITLE
new export format needed: Gaylord version of Passkey

### ISSUE THREAD

**Issue by binary1230** [magfest/hotel#32]
Hotels use different systems to manage their reservations.

The Mark Center used a particular version of a product called Passkey (http://www.lanyon.com/), which we have an exporter for.

The Gaylord also uses Passkey, but it appears there's a newer version they use.  They have sent us a spreadsheet with the fields they expect to see exported and it doesn't match our current exporter.

So, we need to make another exporter that has these fields named correctly.

**Comment by binary1230** [comment]
Here are some of the values (copied from the spreadsheet, and we definitely don't need all of them filled in)

AttendeeType    RecordID    CheckInDate CheckOutDate    NumberofGuests  HotelName   RoomType  
Guest1CheckInDate   Guest1CheckOutDate  Guest1Title Guest1FirstName Guest1MiddleName    Guest1LastName  Guest1Suffix    Guest1Surname   Guest1GivenName Guest1Locale    Guest1CompanyName   Guest1Position  Guest1Address1  Guest1Address2  Guest1City  Guest1State Guest1PostalCode    Guest1Country   Guest1Phone     Guest1Fax   Guest1Email 

SpecialRequest  AccessibleRoom  SmokingPreference   SendAcknowledgement GuaranteeType  
BillingCardNumber   BillingCardExpiration   BillingCardType BillingName BillingAddress1 BillingAddress2 BillingCity BillingState    BillingPostalCode   BillingCountry  BillingPhone    BillingOtherNotes   BillingOtherAmount  BillingOtherReceived    BillingOtherCheckNumber

Guest2CheckInDate   Guest2CheckOutDate  Guest2Title Guest2FirstName Guest2MiddleName    Guest2LastName  Guest2Suffix    Guest2Surname   Guest2GivenName Guest2Position  Guest2Email Guest2BillingName   Guest2BillingCardNumber Guest2BillingCardExpiration Guest2BillingCardType   

Guest3CheckInDate   Guest3CheckOutDate  Guest3Title Guest3FirstName Guest3MiddleName    Guest3LastName  Guest3Suffix    Guest3Surname   Guest3GivenName Guest3Position  Guest3Email Guest3BillingName   Guest3BillingCardNumber Guest3BillingCardExpiration Guest3BillingCardType   

Guest4CheckInDate   Guest4CheckOutDate  Guest4Title Guest4FirstName Guest4MiddleName    Guest4LastName  Guest4Suffix    Guest4Surname   Guest4GivenName Guest4Position  Guest4Email Guest4BillingName   Guest4BillingCardNumber Guest4BillingCardExpiration Guest4BillingCardType   

Guest5CheckInDate   Guest5CheckOutDate  Guest5Title Guest5FirstName Guest5MiddleName    Guest5LastName  Guest5Suffix    Guest5Surname   Guest5GivenName Guest5Position  Guest5Email Guest5BillingName   Guest5BillingCardNumber Guest5BillingCardExpiration Guest5BillingCardType   

AcknowledgementNumber   ReservationTotalCharge  Ext RefrenceID  

CustomField1    CustomField2    CustomField3    CustomField4    CustomField5    CustomField6    CustomField7    CustomField8    CustomField9    CustomField10   CustomField11   CustomField12   CustomField13   CustomField14   CustomField15   SplitFolio  

Guest1ArrivalDate   Guest1ArrivalTime   Guest1ArrivalAirline    Guest1ArrivalFlightNumber   Guest1DepartureDate Guest1DepartureTime Guest1DepartureAirline  Guest1DepartureFlightNumber Guest1OtherTravelDetails    Guest1Transportation    Guest2ArrivalDate   Guest2ArrivalTime  
Guest2ArrivalAirline    Guest2ArrivalFlightNumber   Guest2DepartureDate Guest2DepartureTime Guest2DepartureAirline  Guest2DepartureFlightNumber Guest2OtherTravelDetails    Guest2Transportation  
Guest3ArrivalDate   Guest3ArrivalTime   Guest3ArrivalAirline    Guest3ArrivalFlightNumber   Guest3DepartureDate Guest3DepartureTime Guest3DepartureAirline  Guest3DepartureFlightNumber Guest3OtherTravelDetails    Guest3Transportation    

Guest4ArrivalDate   Guest4ArrivalTime   Guest4ArrivalAirline    Guest4ArrivalFlightNumber   Guest4DepartureDate Guest4DepartureTime Guest4DepartureAirline  Guest4DepartureFlightNumber Guest4OtherTravelDetails    Guest4Transportation    

Guest5ArrivalDate   Guest5ArrivalTime   Guest5ArrivalAirline    Guest5ArrivalFlightNumber   Guest5DepartureDate Guest5DepartureTime Guest5DepartureAirline  Guest5DepartureFlightNumber Guest5OtherTravelDetails    Guest5Transportation

**Comment by binary1230** [comment]
We will have to ask the Gaylord which fields they actually need us to fill in.

**Comment by binary1230** [comment]
for anyone doing the implemention on this, what you'd need to do is make a duplicate of the function in https://github.com/magfest/hotel/blob/master/hotel/site_sections/hotel_assignments.py#L142 and call it maybe 'passkey_v2', and then just output the fields with different names.

**Comment by bds002** [comment]
One of the nice additional columns is : AttendeeType (We can use that to differentiate for  Staff, Bands, Panelist etc....

**Comment by bds002** [comment]
While we are looking at this - the new Passkey format for the Gaylord has an "AccessibleRoom" which I am assuming would be for Handicap Accessibility.... We have 4 or 5 staff that have request that as an option this year..... Would it be to our advantage to make that a simple check box option on the Staff Room request page in the future... (Check here if you need an Accessibilty room)  - and possibly a comment box if they check yes?   --- on the pass key form, that is a different column that other special request.

**Comment by EliAndrewC** [comment]
That does sound worthwhile, so I created #36 to track it.
