### ISSUE TITLE
rename 'hilton_mark_center' to 'passkey'

### ISSUE THREAD

**Issue by binary1230** [magfest/hotel#7]
super-minor-low-priority.

the naming of the export function could be renamed to 'passkey' which is the format that both Gaylord and Mark Center use, and probably a lot of other hotels too.

http://passkey.com/

**Comment by EliAndrewC** [comment]
Oh sweet, I didn't realize that.  I assumed that when the time came I'd need to make a new separate CSV page called `gaylord` in a different format, and then we'd maintain both versions of the spreadsheet output.  If there's one unified system then that's pretty awesome.

**Comment by binary1230** [comment]
yea I need to double check but pretty sure it's the exact same, I remember the spreadsheet looking the same

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/hotel/pull/29
