### ISSUE TITLE
As an admin, I'd like people to be removed from lists when they have been assigned rooms

### ISSUE THREAD

**Issue by RobRuana** [magfest/hotel#81]
We want to avoid duplication of people in lists. The duplication is somewhat by-design, because people may be allocated different rooms on different nights. So we may want a system where we allocate rooms by night. May need some more re-thinking.

**Comment by kitsuta** [comment]
Probably the easiest way to get most of what we want here is to add a filter to the room-eligible selection box, so admins can say like, "only show me people eligible for a room on these nights." That avoids having to redo the whole room assignment workflow (although maybe we want to!)

**Comment by RobRuana** [comment]
Closing as duplicate of #13
